package br.com.tabula.model;

public enum AuditAction {
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_REJECTED,
    PASSWORD_RESET_COMPLETED,
    PASSWORD_CHANGED,
    STATE_UPDATED,
    STATE_UPDATE_REJECTED,
    EMAIL_VERIFICATION_REQUESTED,
    EMAIL_VERIFIED,
    AI_EVENT_DRAFT_GENERATED,
    AI_EVENT_DRAFT_REJECTED
}
